export const indexedDayObjects = [
    [
        {
            dt: 1670695200,
            main: {
                temp: 1,
                feels_like: -2,
                temp_min: 0,
                temp_max: 1,
                pressure: 1004,
                sea_level: 1004,
                grnd_level: 980,
                humidity: 94,
                temp_kf: 1.28,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 3.29, deg: 44, gust: 6.9 },
            visibility: 338,
            pop: 0.2,
            snow: { '3h': 0.28 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-10 18:00:00',
            dt_time: '18:00',
        },
        {
            dt: 1670706000,
            main: {
                temp: 0,
                feels_like: -3,
                temp_min: -0,
                temp_max: 0,
                pressure: 1005,
                sea_level: 1005,
                grnd_level: 979,
                humidity: 95,
                temp_kf: 1.23,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 4.03, deg: 35, gust: 8.26 },
            visibility: 451,
            pop: 0.49,
            snow: { '3h': 0.33 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-10 21:00:00',
            dt_time: '21:00',
        },
    ],
    [
        {
            dt: 1670738400,
            main: {
                temp: -1,
                feels_like: -6,
                temp_min: -1,
                temp_max: -1,
                pressure: 1004,
                sea_level: 1004,
                grnd_level: 977,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 4.45, deg: 3, gust: 9.51 },
            visibility: 145,
            pop: 1,
            snow: { '3h': 3.18 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-11 06:00:00',
            dt_time: '06:00',
        },
        {
            dt: 1670760000,
            main: {
                temp: -1,
                feels_like: -6,
                temp_min: -1,
                temp_max: -1,
                pressure: 1004,
                sea_level: 1004,
                grnd_level: 977,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13d' }],
            clouds: { all: 100 },
            wind: { speed: 4.43, deg: 327, gust: 8.8 },
            visibility: 156,
            pop: 1,
            snow: { '3h': 2.46 },
            sys: { pod: 'd' },
            dt_txt: '2022-12-11 12:00:00',
            dt_time: '12:00',
        },
        {
            dt: 1670792400,
            main: {
                temp: -2,
                feels_like: -8,
                temp_min: -2,
                temp_max: -2,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 979,
                humidity: 96,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 4.74, deg: 276, gust: 9.05 },
            visibility: 179,
            pop: 1,
            snow: { '3h': 1.29 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-11 21:00:00',
            dt_time: '21:00',
        },
    ],
    [
        {
            dt: 1670824800,
            main: {
                temp: -4,
                feels_like: -9,
                temp_min: -4,
                temp_max: -4,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 981,
                humidity: 95,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 4.44, deg: 256, gust: 8.87 },
            visibility: 534,
            pop: 0.28,
            snow: { '3h': 0.32 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-12 06:00:00',
            dt_time: '06:00',
        },
        {
            dt: 1670846400,
            main: {
                temp: -1,
                feels_like: -7,
                temp_min: -1,
                temp_max: -1,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 981,
                humidity: 94,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13d' }],
            clouds: { all: 100 },
            wind: { speed: 4.62, deg: 256, gust: 7.38 },
            visibility: 743,
            pop: 0.94,
            snow: { '3h': 0.38 },
            sys: { pod: 'd' },
            dt_txt: '2022-12-12 12:00:00',
            dt_time: '12:00',
        },
        {
            dt: 1670803200,
            main: {
                temp: -3,
                feels_like: -9,
                temp_min: -3,
                temp_max: -3,
                pressure: 1007,
                sea_level: 1007,
                grnd_level: 980,
                humidity: 95,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 5.1, deg: 270, gust: 9.45 },
            visibility: 480,
            pop: 0.98,
            snow: { '3h': 0.6 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-12 00:00:00',
            dt_time: '00:00',
        },
    ],
    [
        {
            dt: 1670911200,
            main: {
                temp: -5,
                feels_like: -10,
                temp_min: -5,
                temp_max: -5,
                pressure: 1013,
                sea_level: 1013,
                grnd_level: 986,
                humidity: 95,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 3.75, deg: 245, gust: 9.5 },
            visibility: 3926,
            pop: 0.45,
            snow: { '3h': 0.27 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-13 06:00:00',
            dt_time: '06:00',
        },
        {
            dt: 1670932800,
            main: {
                temp: -2,
                feels_like: -7,
                temp_min: -2,
                temp_max: -2,
                pressure: 1015,
                sea_level: 1015,
                grnd_level: 987,
                humidity: 91,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13d' }],
            clouds: { all: 97 },
            wind: { speed: 4.87, deg: 270, gust: 7.46 },
            visibility: 9311,
            pop: 0.21,
            snow: { '3h': 0.12 },
            sys: { pod: 'd' },
            dt_txt: '2022-12-13 12:00:00',
            dt_time: '12:00',
        },
        {
            dt: 1670954400,
            main: {
                temp: -11,
                feels_like: -16,
                temp_min: -11,
                temp_max: -11,
                pressure: 1017,
                sea_level: 1017,
                grnd_level: 989,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 803, main: 'Clouds', description: 'broken clouds', icon: '04n' }],
            clouds: { all: 68 },
            wind: { speed: 2.08, deg: 241, gust: 2.89 },
            visibility: 10000,
            pop: 0,
            sys: { pod: 'n' },
            dt_txt: '2022-12-13 18:00:00',
            dt_time: '18:00',
        },
    ],
    [
        {
            dt: 1670997600,
            main: {
                temp: -13,
                feels_like: -17,
                temp_min: -13,
                temp_max: -13,
                pressure: 1017,
                sea_level: 1017,
                grnd_level: 988,
                humidity: 98,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 96 },
            wind: { speed: 1.76, deg: 230, gust: 1.96 },
            visibility: 8060,
            pop: 0.27,
            snow: { '3h': 0.14 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-14 06:00:00',
            dt_time: '06:00',
        },
        {
            dt: 1671019200,
            main: {
                temp: -5,
                feels_like: -5,
                temp_min: -5,
                temp_max: -5,
                pressure: 1016,
                sea_level: 1016,
                grnd_level: 988,
                humidity: 89,
                temp_kf: 0,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04d' }],
            clouds: { all: 92 },
            wind: { speed: 0.88, deg: 100, gust: 1.19 },
            visibility: 10000,
            pop: 0,
            sys: { pod: 'd' },
            dt_txt: '2022-12-14 12:00:00',
            dt_time: '12:00',
        },
        {
            dt: 1670997600,
            main: {
                temp: -13,
                feels_like: -17,
                temp_min: -13,
                temp_max: -13,
                pressure: 1017,
                sea_level: 1017,
                grnd_level: 988,
                humidity: 98,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 96 },
            wind: { speed: 1.76, deg: 230, gust: 1.96 },
            visibility: 8060,
            pop: 0.27,
            snow: { '3h': 0.14 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-14 06:00:00',
            dt_time: '06:00',
        },
    ],
    [
        {
            dt: 1671084000,
            main: {
                temp: -12,
                feels_like: -12,
                temp_min: -12,
                temp_max: -12,
                pressure: 1014,
                sea_level: 1014,
                grnd_level: 986,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04n' }],
            clouds: { all: 100 },
            wind: { speed: 0.37, deg: 100, gust: 0.55 },
            visibility: 10000,
            pop: 0,
            sys: { pod: 'n' },
            dt_txt: '2022-12-15 06:00:00',
            dt_time: '06:00',
        },
        {
            dt: 1671094800,
            main: {
                temp: -6,
                feels_like: -6,
                temp_min: -6,
                temp_max: -6,
                pressure: 1014,
                sea_level: 1014,
                grnd_level: 987,
                humidity: 88,
                temp_kf: 0,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04d' }],
            clouds: { all: 99 },
            wind: { speed: 0.38, deg: 278, gust: 0.67 },
            visibility: 10000,
            pop: 0.06,
            sys: { pod: 'd' },
            dt_txt: '2022-12-15 09:00:00',
            dt_time: '09:00',
        },
        {
            dt: 1671084000,
            main: {
                temp: -12,
                feels_like: -12,
                temp_min: -12,
                temp_max: -12,
                pressure: 1014,
                sea_level: 1014,
                grnd_level: 986,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04n' }],
            clouds: { all: 100 },
            wind: { speed: 0.37, deg: 100, gust: 0.55 },
            visibility: 10000,
            pop: 0,
            sys: { pod: 'n' },
            dt_txt: '2022-12-15 06:00:00',
            dt_time: '06:00',
        },
    ],
];
