export const indexedDayObjects = [
    [
        {
            dt: 1670544000,
            main: {
                temp: 2,
                feels_like: 2,
                temp_min: 1,
                temp_max: 2,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 985,
                humidity: 85,
                temp_kf: 0.88,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 0.37, deg: 240, gust: 0.86 },
            visibility: 32,
            pop: 0.2,
            snow: { '3h': 0.16 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-09 00:00:00',
        },
        {
            dt: 1670554800,
            main: {
                temp: 1,
                feels_like: 1,
                temp_min: 0,
                temp_max: 1,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 984,
                humidity: 89,
                temp_kf: 0.93,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 99 },
            wind: { speed: 0.54, deg: 169, gust: 1.06 },
            visibility: 10000,
            pop: 0.23,
            snow: { '3h': 0.12 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-09 03:00:00',
        },
        {
            dt: 1670565600,
            main: {
                temp: 0,
                feels_like: 0,
                temp_min: 0,
                temp_max: 0,
                pressure: 1010,
                sea_level: 1010,
                grnd_level: 984,
                humidity: 90,
                temp_kf: 0.7,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04n' }],
            clouds: { all: 93 },
            wind: { speed: 0.69, deg: 144, gust: 1.18 },
            visibility: 10000,
            pop: 0,
            sys: { pod: 'n' },
            dt_txt: '2022-12-09 06:00:00',
        },
        {
            dt: 1670576400,
            main: {
                temp: 1,
                feels_like: -0,
                temp_min: 1,
                temp_max: 1,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 984,
                humidity: 84,
                temp_kf: 0,
            },
            weather: [{ id: 803, main: 'Clouds', description: 'broken clouds', icon: '04d' }],
            clouds: { all: 78 },
            wind: { speed: 1.84, deg: 96, gust: 2.5 },
            visibility: 10000,
            pop: 0,
            sys: { pod: 'd' },
            dt_txt: '2022-12-09 09:00:00',
        },
        {
            dt: 1670587200,
            main: {
                temp: 2,
                feels_like: -1,
                temp_min: 2,
                temp_max: 2,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 981,
                humidity: 79,
                temp_kf: 0,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04d' }],
            clouds: { all: 89 },
            wind: { speed: 3.43, deg: 77, gust: 4.72 },
            visibility: 10000,
            pop: 0.04,
            sys: { pod: 'd' },
            dt_txt: '2022-12-09 12:00:00',
        },
        {
            dt: 1670598000,
            main: {
                temp: 0,
                feels_like: -3,
                temp_min: 0,
                temp_max: 0,
                pressure: 1007,
                sea_level: 1007,
                grnd_level: 980,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 4.02, deg: 77, gust: 7.87 },
            visibility: 464,
            pop: 0.73,
            snow: { '3h': 1.49 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-09 15:00:00',
        },
        {
            dt: 1670608800,
            main: {
                temp: 0,
                feels_like: -3,
                temp_min: 0,
                temp_max: 0,
                pressure: 1005,
                sea_level: 1005,
                grnd_level: 978,
                humidity: 99,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 3.05, deg: 69, gust: 6.59 },
            visibility: 58,
            pop: 0.93,
            snow: { '3h': 4.5 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-09 18:00:00',
        },
        {
            dt: 1670619600,
            main: {
                temp: 0,
                feels_like: -2,
                temp_min: 0,
                temp_max: 0,
                pressure: 1003,
                sea_level: 1003,
                grnd_level: 976,
                humidity: 99,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 2.63, deg: 60, gust: 5.31 },
            visibility: 42,
            pop: 1,
            snow: { '3h': 3.81 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-09 21:00:00',
        },
    ],
    [
        {
            dt: 1670630400,
            main: {
                temp: 0,
                feels_like: -1,
                temp_min: 0,
                temp_max: 0,
                pressure: 1003,
                sea_level: 1003,
                grnd_level: 976,
                humidity: 100,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 1.92, deg: 3, gust: 4.11 },
            visibility: 28,
            pop: 1,
            snow: { '3h': 3.4 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-10 00:00:00',
        },
        {
            dt: 1670641200,
            main: {
                temp: 0,
                feels_like: -1,
                temp_min: 0,
                temp_max: 0,
                pressure: 1004,
                sea_level: 1004,
                grnd_level: 978,
                humidity: 99,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 1.99, deg: 303, gust: 4.37 },
            visibility: 29,
            pop: 1,
            snow: { '3h': 1.82 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-10 03:00:00',
        },
        {
            dt: 1670652000,
            main: {
                temp: 0,
                feels_like: -1,
                temp_min: 0,
                temp_max: 0,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 979,
                humidity: 99,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 1.72, deg: 315, gust: 4.23 },
            visibility: 123,
            pop: 1,
            snow: { '3h': 0.23 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-10 06:00:00',
        },
        {
            dt: 1670662800,
            main: {
                temp: 0,
                feels_like: -1,
                temp_min: 0,
                temp_max: 0,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 982,
                humidity: 99,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13d' }],
            clouds: { all: 100 },
            wind: { speed: 1.6, deg: 329, gust: 2.91 },
            visibility: 617,
            pop: 0.2,
            snow: { '3h': 0.17 },
            sys: { pod: 'd' },
            dt_txt: '2022-12-10 09:00:00',
        },
        {
            dt: 1670673600,
            main: {
                temp: 0,
                feels_like: 0,
                temp_min: 0,
                temp_max: 0,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 981,
                humidity: 100,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13d' }],
            clouds: { all: 100 },
            wind: { speed: 1.24, deg: 22, gust: 2.48 },
            visibility: 400,
            pop: 0.2,
            snow: { '3h': 0.1 },
            sys: { pod: 'd' },
            dt_txt: '2022-12-10 12:00:00',
        },
        {
            dt: 1670684400,
            main: {
                temp: 0,
                feels_like: -1,
                temp_min: 0,
                temp_max: 0,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 982,
                humidity: 99,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 1.74, deg: 54, gust: 3.59 },
            visibility: 417,
            pop: 0.2,
            snow: { '3h': 0.13 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-10 15:00:00',
        },
        {
            dt: 1670695200,
            main: {
                temp: 0,
                feels_like: -2,
                temp_min: 0,
                temp_max: 0,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 982,
                humidity: 99,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 2.53, deg: 64, gust: 5.77 },
            visibility: 135,
            pop: 0.2,
            snow: { '3h': 0.15 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-10 18:00:00',
        },
        {
            dt: 1670706000,
            main: {
                temp: -0,
                feels_like: -4,
                temp_min: -0,
                temp_max: -0,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 982,
                humidity: 98,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 4.06, deg: 61, gust: 7.81 },
            visibility: 301,
            pop: 0.35,
            snow: { '3h': 0.31 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-10 21:00:00',
        },
    ],
    [
        {
            dt: 1670716800,
            main: {
                temp: -0,
                feels_like: -5,
                temp_min: -0,
                temp_max: -0,
                pressure: 1007,
                sea_level: 1007,
                grnd_level: 980,
                humidity: 98,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 4.16, deg: 50, gust: 9.09 },
            visibility: 129,
            pop: 0.94,
            snow: { '3h': 0.97 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-11 00:00:00',
        },
        {
            dt: 1670727600,
            main: {
                temp: -0,
                feels_like: -5,
                temp_min: -0,
                temp_max: -0,
                pressure: 1005,
                sea_level: 1005,
                grnd_level: 979,
                humidity: 98,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 4.72, deg: 40, gust: 10.01 },
            visibility: 134,
            pop: 1,
            snow: { '3h': 2.78 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-11 03:00:00',
        },
        {
            dt: 1670738400,
            main: {
                temp: -1,
                feels_like: -6,
                temp_min: -1,
                temp_max: -1,
                pressure: 1004,
                sea_level: 1004,
                grnd_level: 977,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 5.17, deg: 20, gust: 10.77 },
            visibility: 135,
            pop: 1,
            snow: { '3h': 4.11 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-11 06:00:00',
        },
        {
            dt: 1670749200,
            main: {
                temp: -1,
                feels_like: -6,
                temp_min: -1,
                temp_max: -1,
                pressure: 1004,
                sea_level: 1004,
                grnd_level: 977,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13d' }],
            clouds: { all: 100 },
            wind: { speed: 5.52, deg: 9, gust: 10.86 },
            visibility: 145,
            pop: 1,
            snow: { '3h': 4.53 },
            sys: { pod: 'd' },
            dt_txt: '2022-12-11 09:00:00',
        },
        {
            dt: 1670760000,
            main: {
                temp: -1,
                feels_like: -6,
                temp_min: -1,
                temp_max: -1,
                pressure: 1003,
                sea_level: 1003,
                grnd_level: 976,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13d' }],
            clouds: { all: 100 },
            wind: { speed: 4.78, deg: 354, gust: 9.59 },
            visibility: 151,
            pop: 1,
            snow: { '3h': 2.86 },
            sys: { pod: 'd' },
            dt_txt: '2022-12-11 12:00:00',
        },
        {
            dt: 1670770800,
            main: {
                temp: -1,
                feels_like: -6,
                temp_min: -1,
                temp_max: -1,
                pressure: 1003,
                sea_level: 1003,
                grnd_level: 977,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 4.4, deg: 347, gust: 9.6 },
            visibility: 160,
            pop: 1,
            snow: { '3h': 1.81 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-11 15:00:00',
        },
        {
            dt: 1670781600,
            main: {
                temp: -2,
                feels_like: -6,
                temp_min: -2,
                temp_max: -2,
                pressure: 1005,
                sea_level: 1005,
                grnd_level: 978,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 3.45, deg: 321, gust: 7.8 },
            visibility: 142,
            pop: 1,
            snow: { '3h': 1.38 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-11 18:00:00',
        },
        {
            dt: 1670792400,
            main: {
                temp: -2,
                feels_like: -7,
                temp_min: -2,
                temp_max: -2,
                pressure: 1005,
                sea_level: 1005,
                grnd_level: 978,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 3.03, deg: 305, gust: 6.85 },
            visibility: 152,
            pop: 0.96,
            snow: { '3h': 1.28 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-11 21:00:00',
        },
    ],
    [
        {
            dt: 1670803200,
            main: {
                temp: -3,
                feels_like: -7,
                temp_min: -3,
                temp_max: -3,
                pressure: 1005,
                sea_level: 1005,
                grnd_level: 978,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 2.98, deg: 290, gust: 6.35 },
            visibility: 145,
            pop: 0.98,
            snow: { '3h': 1.38 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-12 00:00:00',
        },
        {
            dt: 1670814000,
            main: {
                temp: -3,
                feels_like: -7,
                temp_min: -3,
                temp_max: -3,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 979,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 3.63, deg: 280, gust: 7.04 },
            visibility: 142,
            pop: 1,
            snow: { '3h': 1.64 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-12 03:00:00',
        },
        {
            dt: 1670824800,
            main: {
                temp: -3,
                feels_like: -8,
                temp_min: -3,
                temp_max: -3,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 979,
                humidity: 96,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 3.83, deg: 267, gust: 7.63 },
            visibility: 197,
            pop: 1,
            snow: { '3h': 0.9 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-12 06:00:00',
        },
        {
            dt: 1670835600,
            main: {
                temp: -3,
                feels_like: -8,
                temp_min: -3,
                temp_max: -3,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 981,
                humidity: 93,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13d' }],
            clouds: { all: 99 },
            wind: { speed: 5.02, deg: 266, gust: 8.16 },
            visibility: 5011,
            pop: 0.67,
            snow: { '3h': 0.37 },
            sys: { pod: 'd' },
            dt_txt: '2022-12-12 09:00:00',
        },
        {
            dt: 1670846400,
            main: {
                temp: -2,
                feels_like: -7,
                temp_min: -2,
                temp_max: -2,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 980,
                humidity: 90,
                temp_kf: 0,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04d' }],
            clouds: { all: 96 },
            wind: { speed: 5.03, deg: 269, gust: 7.82 },
            visibility: 8736,
            pop: 0.41,
            sys: { pod: 'd' },
            dt_txt: '2022-12-12 12:00:00',
        },
        {
            dt: 1670857200,
            main: {
                temp: -3,
                feels_like: -8,
                temp_min: -3,
                temp_max: -3,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 981,
                humidity: 93,
                temp_kf: 0,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04n' }],
            clouds: { all: 99 },
            wind: { speed: 4.14, deg: 255, gust: 8.9 },
            visibility: 10000,
            pop: 0.05,
            sys: { pod: 'n' },
            dt_txt: '2022-12-12 15:00:00',
        },
        {
            dt: 1670868000,
            main: {
                temp: -7,
                feels_like: -12,
                temp_min: -7,
                temp_max: -7,
                pressure: 1010,
                sea_level: 1010,
                grnd_level: 983,
                humidity: 95,
                temp_kf: 0,
            },
            weather: [{ id: 803, main: 'Clouds', description: 'broken clouds', icon: '04n' }],
            clouds: { all: 84 },
            wind: { speed: 3.05, deg: 240, gust: 6.2 },
            visibility: 10000,
            pop: 0,
            sys: { pod: 'n' },
            dt_txt: '2022-12-12 18:00:00',
        },
        {
            dt: 1670878800,
            main: {
                temp: -6,
                feels_like: -11,
                temp_min: -6,
                temp_max: -6,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 983,
                humidity: 94,
                temp_kf: 0,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04n' }],
            clouds: { all: 100 },
            wind: { speed: 2.36, deg: 237, gust: 4.66 },
            visibility: 9555,
            pop: 0,
            sys: { pod: 'n' },
            dt_txt: '2022-12-12 21:00:00',
        },
    ],
    [
        {
            dt: 1670889600,
            main: {
                temp: -6,
                feels_like: -10,
                temp_min: -6,
                temp_max: -6,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 983,
                humidity: 96,
                temp_kf: 0,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04n' }],
            clouds: { all: 100 },
            wind: { speed: 2.29, deg: 238, gust: 4.5 },
            visibility: 760,
            pop: 0.05,
            sys: { pod: 'n' },
            dt_txt: '2022-12-13 00:00:00',
        },
        {
            dt: 1670900400,
            main: {
                temp: -9,
                feels_like: -13,
                temp_min: -9,
                temp_max: -9,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 983,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04n' }],
            clouds: { all: 89 },
            wind: { speed: 2.12, deg: 234, gust: 3.19 },
            visibility: 6434,
            pop: 0.13,
            sys: { pod: 'n' },
            dt_txt: '2022-12-13 03:00:00',
        },
        {
            dt: 1670911200,
            main: {
                temp: -7,
                feels_like: -11,
                temp_min: -7,
                temp_max: -7,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 984,
                humidity: 96,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 93 },
            wind: { speed: 2.12, deg: 240, gust: 3.59 },
            visibility: 3450,
            pop: 0.35,
            snow: { '3h': 0.12 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-13 06:00:00',
        },
        {
            dt: 1670922000,
            main: {
                temp: -4,
                feels_like: -8,
                temp_min: -4,
                temp_max: -4,
                pressure: 1012,
                sea_level: 1012,
                grnd_level: 984,
                humidity: 95,
                temp_kf: 0,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04d' }],
            clouds: { all: 100 },
            wind: { speed: 2.61, deg: 260, gust: 5.16 },
            visibility: 1607,
            pop: 0,
            sys: { pod: 'd' },
            dt_txt: '2022-12-13 09:00:00',
        },
        {
            dt: 1670932800,
            main: {
                temp: -2,
                feels_like: -5,
                temp_min: -2,
                temp_max: -2,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 983,
                humidity: 94,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13d' }],
            clouds: { all: 100 },
            wind: { speed: 2.63, deg: 292, gust: 4.28 },
            visibility: 436,
            pop: 0.56,
            snow: { '3h': 0.7 },
            sys: { pod: 'd' },
            dt_txt: '2022-12-13 12:00:00',
        },
        {
            dt: 1670943600,
            main: {
                temp: -2,
                feels_like: -4,
                temp_min: -2,
                temp_max: -2,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 984,
                humidity: 98,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 1.48, deg: 301, gust: 4.46 },
            visibility: 122,
            pop: 1,
            snow: { '3h': 1.06 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-13 15:00:00',
        },
        {
            dt: 1670954400,
            main: {
                temp: -2,
                feels_like: -2,
                temp_min: -2,
                temp_max: -2,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 984,
                humidity: 98,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 1.27, deg: 318, gust: 3.75 },
            visibility: 121,
            pop: 1,
            snow: { '3h': 1.81 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-13 18:00:00',
        },
        {
            dt: 1670965200,
            main: {
                temp: -2,
                feels_like: -6,
                temp_min: -2,
                temp_max: -2,
                pressure: 1012,
                sea_level: 1012,
                grnd_level: 985,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 3.09, deg: 326, gust: 7.87 },
            visibility: 152,
            pop: 1,
            snow: { '3h': 1.87 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-13 21:00:00',
        },
    ],
];
