const obj = {
    cod: '200',
    message: 0,
    cnt: 40,
    list: [
        {
            dt: 1670436000,
            main: {
                temp: 276.69,
                feels_like: 272.51,
                temp_min: 274.69,
                temp_max: 276.69,
                pressure: 1010,
                sea_level: 1010,
                grnd_level: 985,
                humidity: 78,
                temp_kf: 2,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 75,
            },
            wind: {
                speed: 5.31,
                deg: 241,
                gust: 11.72,
            },
            visibility: 10000,
            pop: 0.01,
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-07 18:00:00',
        },
        {
            dt: 1670446800,
            main: {
                temp: 275.95,
                feels_like: 271.83,
                temp_min: 274.47,
                temp_max: 275.95,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 986,
                humidity: 80,
                temp_kf: 1.48,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 83,
            },
            wind: {
                speed: 4.82,
                deg: 234,
                gust: 10.99,
            },
            visibility: 10000,
            pop: 0.08,
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-07 21:00:00',
        },
        {
            dt: 1670457600,
            main: {
                temp: 275,
                feels_like: 271.04,
                temp_min: 274.15,
                temp_max: 275,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 986,
                humidity: 82,
                temp_kf: 0.85,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 91,
            },
            wind: {
                speed: 4.15,
                deg: 232,
                gust: 9.65,
            },
            visibility: 10000,
            pop: 0.01,
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-08 00:00:00',
        },
        {
            dt: 1670468400,
            main: {
                temp: 273.77,
                feels_like: 270.03,
                temp_min: 273.77,
                temp_max: 273.77,
                pressure: 1013,
                sea_level: 1013,
                grnd_level: 986,
                humidity: 81,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 71,
            },
            wind: {
                speed: 3.45,
                deg: 235,
                gust: 7.72,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-08 03:00:00',
        },
        {
            dt: 1670479200,
            main: {
                temp: 273.48,
                feels_like: 270.64,
                temp_min: 273.48,
                temp_max: 273.48,
                pressure: 1013,
                sea_level: 1013,
                grnd_level: 986,
                humidity: 82,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 85,
            },
            wind: {
                speed: 2.38,
                deg: 224,
                gust: 4.9,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-08 06:00:00',
        },
        {
            dt: 1670490000,
            main: {
                temp: 275.86,
                feels_like: 273.16,
                temp_min: 275.86,
                temp_max: 275.86,
                pressure: 1013,
                sea_level: 1013,
                grnd_level: 986,
                humidity: 71,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 70,
            },
            wind: {
                speed: 2.7,
                deg: 215,
                gust: 6.73,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2022-12-08 09:00:00',
        },
        {
            dt: 1670500800,
            main: {
                temp: 277.86,
                feels_like: 275.71,
                temp_min: 277.86,
                temp_max: 277.86,
                pressure: 1012,
                sea_level: 1012,
                grnd_level: 985,
                humidity: 63,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 75,
            },
            wind: {
                speed: 2.5,
                deg: 223,
                gust: 6.1,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2022-12-08 12:00:00',
        },
        {
            dt: 1670511600,
            main: {
                temp: 275.12,
                feels_like: 275.12,
                temp_min: 275.12,
                temp_max: 275.12,
                pressure: 1012,
                sea_level: 1012,
                grnd_level: 985,
                humidity: 75,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 73,
            },
            wind: {
                speed: 0.63,
                deg: 139,
                gust: 0.98,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-08 15:00:00',
        },
        {
            dt: 1670522400,
            main: {
                temp: 274.41,
                feels_like: 274.41,
                temp_min: 274.41,
                temp_max: 274.41,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 984,
                humidity: 78,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 87,
            },
            wind: {
                speed: 0.37,
                deg: 164,
                gust: 0.59,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-08 18:00:00',
        },
        {
            dt: 1670533200,
            main: {
                temp: 273.97,
                feels_like: 273.97,
                temp_min: 273.97,
                temp_max: 273.97,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 984,
                humidity: 80,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 0.3,
                deg: 310,
                gust: 0.62,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-08 21:00:00',
        },
        {
            dt: 1670544000,
            main: {
                temp: 273.98,
                feels_like: 273.98,
                temp_min: 273.98,
                temp_max: 273.98,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 984,
                humidity: 81,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 98,
            },
            wind: {
                speed: 1.01,
                deg: 112,
                gust: 1.08,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-09 00:00:00',
        },
        {
            dt: 1670554800,
            main: {
                temp: 273.47,
                feels_like: 273.47,
                temp_min: 273.47,
                temp_max: 273.47,
                pressure: 1010,
                sea_level: 1010,
                grnd_level: 983,
                humidity: 83,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 99,
            },
            wind: {
                speed: 1.3,
                deg: 96,
                gust: 1.25,
            },
            visibility: 10000,
            pop: 0.08,
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-09 03:00:00',
        },
        {
            dt: 1670565600,
            main: {
                temp: 273.02,
                feels_like: 273.02,
                temp_min: 273.02,
                temp_max: 273.02,
                pressure: 1010,
                sea_level: 1010,
                grnd_level: 983,
                humidity: 83,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 96,
            },
            wind: {
                speed: 1.04,
                deg: 91,
                gust: 1.18,
            },
            visibility: 10000,
            pop: 0.03,
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-09 06:00:00',
        },
        {
            dt: 1670576400,
            main: {
                temp: 274.79,
                feels_like: 273.44,
                temp_min: 274.79,
                temp_max: 274.79,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 983,
                humidity: 75,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 95,
            },
            wind: {
                speed: 1.39,
                deg: 81,
                gust: 1.76,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2022-12-09 09:00:00',
        },
        {
            dt: 1670587200,
            main: {
                temp: 275.4,
                feels_like: 272.55,
                temp_min: 275.4,
                temp_max: 275.4,
                pressure: 1007,
                sea_level: 1007,
                grnd_level: 980,
                humidity: 77,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 91,
            },
            wind: {
                speed: 2.77,
                deg: 78,
                gust: 4.43,
            },
            visibility: 10000,
            pop: 0.12,
            sys: {
                pod: 'd',
            },
            dt_txt: '2022-12-09 12:00:00',
        },
        {
            dt: 1670598000,
            main: {
                temp: 273.63,
                feels_like: 270.76,
                temp_min: 273.63,
                temp_max: 273.63,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 980,
                humidity: 99,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 601,
                    main: 'Snow',
                    description: 'snow',
                    icon: '13n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 2.44,
                deg: 59,
                gust: 5.51,
            },
            visibility: 96,
            pop: 0.88,
            snow: {
                '3h': 2.79,
            },
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-09 15:00:00',
        },
        {
            dt: 1670608800,
            main: {
                temp: 273.66,
                feels_like: 271.31,
                temp_min: 273.66,
                temp_max: 273.66,
                pressure: 1005,
                sea_level: 1005,
                grnd_level: 979,
                humidity: 99,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 601,
                    main: 'Snow',
                    description: 'snow',
                    icon: '13n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 1.98,
                deg: 52,
                gust: 4.29,
            },
            visibility: 58,
            pop: 0.95,
            snow: {
                '3h': 2.66,
            },
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-09 18:00:00',
        },
        {
            dt: 1670619600,
            main: {
                temp: 273.78,
                feels_like: 272.16,
                temp_min: 273.78,
                temp_max: 273.78,
                pressure: 1005,
                sea_level: 1005,
                grnd_level: 978,
                humidity: 99,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 601,
                    main: 'Snow',
                    description: 'snow',
                    icon: '13n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 1.47,
                deg: 2,
                gust: 3.16,
            },
            visibility: 25,
            pop: 0.75,
            snow: {
                '3h': 1.56,
            },
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-09 21:00:00',
        },
        {
            dt: 1670630400,
            main: {
                temp: 273.76,
                feels_like: 271.47,
                temp_min: 273.76,
                temp_max: 273.76,
                pressure: 1005,
                sea_level: 1005,
                grnd_level: 979,
                humidity: 99,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 601,
                    main: 'Snow',
                    description: 'snow',
                    icon: '13n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 1.95,
                deg: 330,
                gust: 4.79,
            },
            visibility: 45,
            pop: 0.8,
            snow: {
                '3h': 1.85,
            },
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-10 00:00:00',
        },
        {
            dt: 1670641200,
            main: {
                temp: 273.49,
                feels_like: 270.86,
                temp_min: 273.49,
                temp_max: 273.49,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 980,
                humidity: 98,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 600,
                    main: 'Snow',
                    description: 'light snow',
                    icon: '13n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 2.19,
                deg: 331,
                gust: 5.56,
            },
            visibility: 2689,
            pop: 0.64,
            snow: {
                '3h': 0.67,
            },
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-10 03:00:00',
        },
        {
            dt: 1670652000,
            main: {
                temp: 272.76,
                feels_like: 269.73,
                temp_min: 272.76,
                temp_max: 272.76,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 981,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 600,
                    main: 'Snow',
                    description: 'light snow',
                    icon: '13n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 2.44,
                deg: 321,
                gust: 4.94,
            },
            visibility: 3424,
            pop: 0.53,
            snow: {
                '3h': 0.47,
            },
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-10 06:00:00',
        },
        {
            dt: 1670662800,
            main: {
                temp: 273.04,
                feels_like: 269.95,
                temp_min: 273.04,
                temp_max: 273.04,
                pressure: 1010,
                sea_level: 1010,
                grnd_level: 983,
                humidity: 96,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 600,
                    main: 'Snow',
                    description: 'light snow',
                    icon: '13d',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 2.55,
                deg: 332,
                gust: 3.47,
            },
            visibility: 2011,
            pop: 0.23,
            snow: {
                '3h': 0.21,
            },
            sys: {
                pod: 'd',
            },
            dt_txt: '2022-12-10 09:00:00',
        },
        {
            dt: 1670673600,
            main: {
                temp: 273.26,
                feels_like: 270.64,
                temp_min: 273.26,
                temp_max: 273.26,
                pressure: 1010,
                sea_level: 1010,
                grnd_level: 983,
                humidity: 90,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 2.15,
                deg: 351,
                gust: 2.63,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2022-12-10 12:00:00',
        },
        {
            dt: 1670684400,
            main: {
                temp: 272.84,
                feels_like: 270.58,
                temp_min: 272.84,
                temp_max: 272.84,
                pressure: 1012,
                sea_level: 1012,
                grnd_level: 985,
                humidity: 88,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 1.81,
                deg: 31,
                gust: 2.79,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-10 15:00:00',
        },
        {
            dt: 1670695200,
            main: {
                temp: 272.6,
                feels_like: 270.05,
                temp_min: 272.6,
                temp_max: 272.6,
                pressure: 1013,
                sea_level: 1013,
                grnd_level: 985,
                humidity: 89,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 2,
                deg: 54,
                gust: 3.89,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-10 18:00:00',
        },
        {
            dt: 1670706000,
            main: {
                temp: 272.4,
                feels_like: 268.37,
                temp_min: 272.4,
                temp_max: 272.4,
                pressure: 1012,
                sea_level: 1012,
                grnd_level: 985,
                humidity: 90,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 3.44,
                deg: 71,
                gust: 6.51,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-10 21:00:00',
        },
        {
            dt: 1670716800,
            main: {
                temp: 272.42,
                feels_like: 267.78,
                temp_min: 272.42,
                temp_max: 272.42,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 984,
                humidity: 93,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 4.28,
                deg: 66,
                gust: 8.18,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-11 00:00:00',
        },
        {
            dt: 1670727600,
            main: {
                temp: 272.4,
                feels_like: 267.03,
                temp_min: 272.4,
                temp_max: 272.4,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 982,
                humidity: 92,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 5.46,
                deg: 71,
                gust: 11.15,
            },
            visibility: 4835,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-11 03:00:00',
        },
        {
            dt: 1670738400,
            main: {
                temp: 272.27,
                feels_like: 266.28,
                temp_min: 272.27,
                temp_max: 272.27,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 979,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 600,
                    main: 'Snow',
                    description: 'light snow',
                    icon: '13n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 6.62,
                deg: 66,
                gust: 13.6,
            },
            visibility: 150,
            pop: 0.53,
            snow: {
                '3h': 0.9,
            },
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-11 06:00:00',
        },
        {
            dt: 1670749200,
            main: {
                temp: 272.75,
                feels_like: 266.7,
                temp_min: 272.75,
                temp_max: 272.75,
                pressure: 1002,
                sea_level: 1002,
                grnd_level: 975,
                humidity: 98,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 601,
                    main: 'Snow',
                    description: 'snow',
                    icon: '13d',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 7.04,
                deg: 58,
                gust: 14.86,
            },
            visibility: 115,
            pop: 1,
            snow: {
                '3h': 5.88,
            },
            sys: {
                pod: 'd',
            },
            dt_txt: '2022-12-11 09:00:00',
        },
        {
            dt: 1670760000,
            main: {
                temp: 273.16,
                feels_like: 267.95,
                temp_min: 273.16,
                temp_max: 273.16,
                pressure: 999,
                sea_level: 999,
                grnd_level: 973,
                humidity: 98,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 601,
                    main: 'Snow',
                    description: 'snow',
                    icon: '13d',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 5.54,
                deg: 54,
                gust: 11.5,
            },
            visibility: 130,
            pop: 1,
            snow: {
                '3h': 5.9,
            },
            sys: {
                pod: 'd',
            },
            dt_txt: '2022-12-11 12:00:00',
        },
        {
            dt: 1670770800,
            main: {
                temp: 273.21,
                feels_like: 269.59,
                temp_min: 273.21,
                temp_max: 273.21,
                pressure: 999,
                sea_level: 999,
                grnd_level: 972,
                humidity: 98,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 600,
                    main: 'Snow',
                    description: 'light snow',
                    icon: '13n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 3.15,
                deg: 36,
                gust: 6.91,
            },
            visibility: 246,
            pop: 0.7,
            snow: {
                '3h': 1.22,
            },
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-11 15:00:00',
        },
        {
            dt: 1670781600,
            main: {
                temp: 273.02,
                feels_like: 270.67,
                temp_min: 273.02,
                temp_max: 273.02,
                pressure: 1000,
                sea_level: 1000,
                grnd_level: 973,
                humidity: 98,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 600,
                    main: 'Snow',
                    description: 'light snow',
                    icon: '13n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 1.9,
                deg: 317,
                gust: 3.84,
            },
            visibility: 413,
            pop: 0.68,
            snow: {
                '3h': 0.9,
            },
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-11 18:00:00',
        },
        {
            dt: 1670792400,
            main: {
                temp: 272.62,
                feels_like: 269.49,
                temp_min: 272.62,
                temp_max: 272.62,
                pressure: 1000,
                sea_level: 1000,
                grnd_level: 974,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 2.51,
                deg: 289,
                gust: 5.09,
            },
            visibility: 10000,
            pop: 0.07,
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-11 21:00:00',
        },
        {
            dt: 1670803200,
            main: {
                temp: 271.91,
                feels_like: 268.72,
                temp_min: 271.91,
                temp_max: 271.91,
                pressure: 1001,
                sea_level: 1001,
                grnd_level: 974,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 2.44,
                deg: 287,
                gust: 4.79,
            },
            visibility: 9765,
            pop: 0.01,
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-12 00:00:00',
        },
        {
            dt: 1670814000,
            main: {
                temp: 271.05,
                feels_like: 267.74,
                temp_min: 271.05,
                temp_max: 271.05,
                pressure: 999,
                sea_level: 999,
                grnd_level: 972,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 2.41,
                deg: 314,
                gust: 4.83,
            },
            visibility: 8870,
            pop: 0.16,
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-12 03:00:00',
        },
        {
            dt: 1670824800,
            main: {
                temp: 270.46,
                feels_like: 266.11,
                temp_min: 270.46,
                temp_max: 270.46,
                pressure: 999,
                sea_level: 999,
                grnd_level: 972,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 601,
                    main: 'Snow',
                    description: 'snow',
                    icon: '13n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 3.33,
                deg: 286,
                gust: 5.56,
            },
            visibility: 118,
            pop: 0.94,
            snow: {
                '3h': 2.81,
            },
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-12 06:00:00',
        },
        {
            dt: 1670835600,
            main: {
                temp: 270.18,
                feels_like: 265.69,
                temp_min: 270.18,
                temp_max: 270.18,
                pressure: 999,
                sea_level: 999,
                grnd_level: 972,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 601,
                    main: 'Snow',
                    description: 'snow',
                    icon: '13d',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 3.42,
                deg: 276,
                gust: 6.23,
            },
            visibility: 127,
            pop: 1,
            snow: {
                '3h': 6.53,
            },
            sys: {
                pod: 'd',
            },
            dt_txt: '2022-12-12 09:00:00',
        },
        {
            dt: 1670846400,
            main: {
                temp: 270.34,
                feels_like: 264.19,
                temp_min: 270.34,
                temp_max: 270.34,
                pressure: 998,
                sea_level: 998,
                grnd_level: 972,
                humidity: 96,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 601,
                    main: 'Snow',
                    description: 'snow',
                    icon: '13d',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 5.89,
                deg: 263,
                gust: 9.83,
            },
            visibility: 221,
            pop: 1,
            snow: {
                '3h': 2.9,
            },
            sys: {
                pod: 'd',
            },
            dt_txt: '2022-12-12 12:00:00',
        },
        {
            dt: 1670857200,
            main: {
                temp: 269.82,
                feels_like: 263.47,
                temp_min: 269.82,
                temp_max: 269.82,
                pressure: 999,
                sea_level: 999,
                grnd_level: 972,
                humidity: 91,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 600,
                    main: 'Snow',
                    description: 'light snow',
                    icon: '13n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 6.01,
                deg: 251,
                gust: 11.64,
            },
            visibility: 10000,
            pop: 0.66,
            snow: {
                '3h': 0.42,
            },
            sys: {
                pod: 'n',
            },
            dt_txt: '2022-12-12 15:00:00',
        },
    ],
    city: {
        id: 3094802,
        name: 'Krakow',
        coord: {
            lat: 50.0833,
            lon: 19.9167,
        },
        country: 'PL',
        population: 755050,
        timezone: 3600,
        sunrise: 1670394286,
        sunset: 1670423938,
    },
};

var testArr = [
    {
        dt: 1670436000,
        main: {
            temp: 276.69,
            feels_like: 272.51,
            temp_min: 274.69,
            temp_max: 276.69,
            pressure: 1010,
            sea_level: 1010,
            grnd_level: 985,
            humidity: 78,
            temp_kf: 2,
        },
        weather: [
            {
                id: 803,
                main: 'Clouds',
                description: 'broken clouds',
                icon: '04n',
            },
        ],
        clouds: {
            all: 75,
        },
        wind: {
            speed: 5.31,
            deg: 241,
            gust: 11.72,
        },
        visibility: 10000,
        pop: 0.01,
        sys: {
            pod: 'n',
        },
        dt_txt: '2022-12-07 18:00:00',
    },
    {
        dt: 1670446800,
        main: {
            temp: 275.95,
            feels_like: 271.83,
            temp_min: 274.47,
            temp_max: 275.95,
            pressure: 1011,
            sea_level: 1011,
            grnd_level: 986,
            humidity: 80,
            temp_kf: 1.48,
        },
        weather: [
            {
                id: 803,
                main: 'Clouds',
                description: 'broken clouds',
                icon: '04n',
            },
        ],
        clouds: {
            all: 83,
        },
        wind: {
            speed: 4.82,
            deg: 234,
            gust: 10.99,
        },
        visibility: 10000,
        pop: 0.08,
        sys: {
            pod: 'n',
        },
        dt_txt: '2022-12-07 21:00:00',
    },
    {
        dt: 1670457600,
        main: {
            temp: 275,
            feels_like: 271.04,
            temp_min: 274.15,
            temp_max: 275,
            pressure: 1011,
            sea_level: 1011,
            grnd_level: 986,
            humidity: 82,
            temp_kf: 0.85,
        },
        weather: [
            {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04n',
            },
        ],
        clouds: {
            all: 91,
        },
        wind: {
            speed: 4.15,
            deg: 232,
            gust: 9.65,
        },
        visibility: 10000,
        pop: 0.01,
        sys: {
            pod: 'n',
        },
        dt_txt: '2022-12-08 00:00:00',
    },
    {
        dt: 1670468400,
        main: {
            temp: 273.77,
            feels_like: 270.03,
            temp_min: 273.77,
            temp_max: 273.77,
            pressure: 1013,
            sea_level: 1013,
            grnd_level: 986,
            humidity: 81,
            temp_kf: 0,
        },
        weather: [
            {
                id: 803,
                main: 'Clouds',
                description: 'broken clouds',
                icon: '04n',
            },
        ],
        clouds: {
            all: 71,
        },
        wind: {
            speed: 3.45,
            deg: 235,
            gust: 7.72,
        },
        visibility: 10000,
        pop: 0,
        sys: {
            pod: 'n',
        },
        dt_txt: '2022-12-08 03:00:00',
    },
];

var testArr1 = {
    cod: '200',
    message: 0,
    cnt: 40,
    list: [
        {
            dt: 1670522400,
            main: {
                temp: 275.35,
                feels_like: 275.35,
                temp_min: 274.46,
                temp_max: 275.35,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 985,
                humidity: 88,
                temp_kf: 0.89,
            },
            weather: [{ id: 803, main: 'Clouds', description: 'broken clouds', icon: '04n' }],
            clouds: { all: 75 },
            wind: { speed: 1.1, deg: 290, gust: 1.19 },
            visibility: 10000,
            pop: 0,
            sys: { pod: 'n' },
            dt_txt: '2022-12-08 18:00:00',
        },
        {
            dt: 1670533200,
            main: {
                temp: 274.83,
                feels_like: 274.83,
                temp_min: 273.78,
                temp_max: 274.83,
                pressure: 1010,
                sea_level: 1010,
                grnd_level: 985,
                humidity: 90,
                temp_kf: 1.05,
            },
            weather: [{ id: 803, main: 'Clouds', description: 'broken clouds', icon: '04n' }],
            clouds: { all: 83 },
            wind: { speed: 0.91, deg: 305, gust: 1.02 },
            visibility: 10000,
            pop: 0,
            sys: { pod: 'n' },
            dt_txt: '2022-12-08 21:00:00',
        },
        {
            dt: 1670544000,
            main: {
                temp: 274.61,
                feels_like: 274.61,
                temp_min: 274.24,
                temp_max: 274.61,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 985,
                humidity: 95,
                temp_kf: 0.37,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 92 },
            wind: { speed: 0.13, deg: 162, gust: 0.57 },
            visibility: 132,
            pop: 0.24,
            snow: { '3h': 0.17 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-09 00:00:00',
        },
        {
            dt: 1670554800,
            main: {
                temp: 273.95,
                feels_like: 273.95,
                temp_min: 273.95,
                temp_max: 273.95,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 984,
                humidity: 96,
                temp_kf: 0,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04n' }],
            clouds: { all: 99 },
            wind: { speed: 0.78, deg: 120, gust: 1.17 },
            visibility: 10000,
            pop: 0.19,
            sys: { pod: 'n' },
            dt_txt: '2022-12-09 03:00:00',
        },
        {
            dt: 1670565600,
            main: {
                temp: 273.13,
                feels_like: 273.13,
                temp_min: 273.13,
                temp_max: 273.13,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 984,
                humidity: 91,
                temp_kf: 0,
            },
            weather: [{ id: 803, main: 'Clouds', description: 'broken clouds', icon: '04n' }],
            clouds: { all: 78 },
            wind: { speed: 1.2, deg: 108, gust: 1.67 },
            visibility: 10000,
            pop: 0,
            sys: { pod: 'n' },
            dt_txt: '2022-12-09 06:00:00',
        },
        {
            dt: 1670576400,
            main: {
                temp: 274.34,
                feels_like: 272.74,
                temp_min: 274.34,
                temp_max: 274.34,
                pressure: 1010,
                sea_level: 1010,
                grnd_level: 984,
                humidity: 82,
                temp_kf: 0,
            },
            weather: [{ id: 803, main: 'Clouds', description: 'broken clouds', icon: '04d' }],
            clouds: { all: 79 },
            wind: { speed: 1.51, deg: 71, gust: 1.87 },
            visibility: 10000,
            pop: 0,
            sys: { pod: 'd' },
            dt_txt: '2022-12-09 09:00:00',
        },
        {
            dt: 1670587200,
            main: {
                temp: 275.37,
                feels_like: 271.79,
                temp_min: 275.37,
                temp_max: 275.37,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 981,
                humidity: 77,
                temp_kf: 0,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04d' }],
            clouds: { all: 89 },
            wind: { speed: 3.71, deg: 67, gust: 4.99 },
            visibility: 10000,
            pop: 0.04,
            sys: { pod: 'd' },
            dt_txt: '2022-12-09 12:00:00',
        },
        {
            dt: 1670598000,
            main: {
                temp: 273.53,
                feels_like: 268.98,
                temp_min: 273.53,
                temp_max: 273.53,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 979,
                humidity: 98,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 4.55, deg: 75, gust: 8.58 },
            visibility: 258,
            pop: 0.73,
            snow: { '3h': 2.33 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-09 15:00:00',
        },
        {
            dt: 1670608800,
            main: {
                temp: 273.46,
                feels_like: 270,
                temp_min: 273.46,
                temp_max: 273.46,
                pressure: 1005,
                sea_level: 1005,
                grnd_level: 978,
                humidity: 99,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 3.03, deg: 66, gust: 6.53 },
            visibility: 113,
            pop: 0.93,
            snow: { '3h': 4.04 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-09 18:00:00',
        },
        {
            dt: 1670619600,
            main: {
                temp: 273.65,
                feels_like: 271.61,
                temp_min: 273.65,
                temp_max: 273.65,
                pressure: 1003,
                sea_level: 1003,
                grnd_level: 977,
                humidity: 100,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 1.74, deg: 46, gust: 3.56 },
            visibility: 58,
            pop: 1,
            snow: { '3h': 3.17 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-09 21:00:00',
        },
        {
            dt: 1670630400,
            main: {
                temp: 273.75,
                feels_like: 271.84,
                temp_min: 273.75,
                temp_max: 273.75,
                pressure: 1003,
                sea_level: 1003,
                grnd_level: 976,
                humidity: 100,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 1.66, deg: 19, gust: 3.97 },
            visibility: 36,
            pop: 1,
            snow: { '3h': 2.75 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-10 00:00:00',
        },
        {
            dt: 1670641200,
            main: {
                temp: 273.7,
                feels_like: 271.81,
                temp_min: 273.7,
                temp_max: 273.7,
                pressure: 1003,
                sea_level: 1003,
                grnd_level: 976,
                humidity: 100,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 1.64, deg: 319, gust: 3.77 },
            visibility: 25,
            pop: 0.93,
            snow: { '3h': 3.22 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-10 03:00:00',
        },
        {
            dt: 1670652000,
            main: {
                temp: 273.77,
                feels_like: 271.58,
                temp_min: 273.77,
                temp_max: 273.77,
                pressure: 1005,
                sea_level: 1005,
                grnd_level: 978,
                humidity: 99,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 1.87, deg: 302, gust: 4.72 },
            visibility: 38,
            pop: 0.92,
            snow: { '3h': 0.72 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-10 06:00:00',
        },
        {
            dt: 1670662800,
            main: {
                temp: 273.79,
                feels_like: 271.96,
                temp_min: 273.79,
                temp_max: 273.79,
                pressure: 1007,
                sea_level: 1007,
                grnd_level: 980,
                humidity: 100,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13d' }],
            clouds: { all: 100 },
            wind: { speed: 1.61, deg: 284, gust: 3.45 },
            visibility: 93,
            pop: 0.22,
            snow: { '3h': 0.19 },
            sys: { pod: 'd' },
            dt_txt: '2022-12-10 09:00:00',
        },
        {
            dt: 1670673600,
            main: {
                temp: 273.9,
                feels_like: 272.34,
                temp_min: 273.9,
                temp_max: 273.9,
                pressure: 1007,
                sea_level: 1007,
                grnd_level: 981,
                humidity: 100,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13d' }],
            clouds: { all: 100 },
            wind: { speed: 1.44, deg: 288, gust: 2.96 },
            visibility: 1265,
            pop: 0.2,
            snow: { '3h': 0.11 },
            sys: { pod: 'd' },
            dt_txt: '2022-12-10 12:00:00',
        },
        {
            dt: 1670684400,
            main: {
                temp: 273.71,
                feels_like: 273.71,
                temp_min: 273.71,
                temp_max: 273.71,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 982,
                humidity: 99,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 0.61, deg: 2, gust: 2.29 },
            visibility: 463,
            pop: 0.2,
            snow: { '3h': 0.11 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-10 15:00:00',
        },
        {
            dt: 1670695200,
            main: {
                temp: 273.54,
                feels_like: 271.1,
                temp_min: 273.54,
                temp_max: 273.54,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 982,
                humidity: 99,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 2.04, deg: 39, gust: 5 },
            visibility: 276,
            pop: 0.2,
            snow: { '3h': 0.18 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-10 18:00:00',
        },
        {
            dt: 1670706000,
            main: {
                temp: 273.36,
                feels_like: 269.78,
                temp_min: 273.36,
                temp_max: 273.36,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 982,
                humidity: 99,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 3.14, deg: 50, gust: 6.69 },
            visibility: 220,
            pop: 0.47,
            snow: { '3h': 0.34 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-10 21:00:00',
        },
        {
            dt: 1670716800,
            main: {
                temp: 272.95,
                feels_like: 268.89,
                temp_min: 272.95,
                temp_max: 272.95,
                pressure: 1007,
                sea_level: 1007,
                grnd_level: 980,
                humidity: 98,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 3.63, deg: 55, gust: 8.62 },
            visibility: 165,
            pop: 0.6,
            snow: { '3h': 0.53 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-11 00:00:00',
        },
        {
            dt: 1670727600,
            main: {
                temp: 272.7,
                feels_like: 268.09,
                temp_min: 272.7,
                temp_max: 272.7,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 979,
                humidity: 98,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 4.32, deg: 42, gust: 9.62 },
            visibility: 126,
            pop: 0.93,
            snow: { '3h': 1.85 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-11 03:00:00',
        },
        {
            dt: 1670738400,
            main: {
                temp: 272.29,
                feels_like: 266.96,
                temp_min: 272.29,
                temp_max: 272.29,
                pressure: 1004,
                sea_level: 1004,
                grnd_level: 977,
                humidity: 98,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 5.34, deg: 27, gust: 11.4 },
            visibility: 126,
            pop: 1,
            snow: { '3h': 4.29 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-11 06:00:00',
        },
        {
            dt: 1670749200,
            main: {
                temp: 272.2,
                feels_like: 266.72,
                temp_min: 272.2,
                temp_max: 272.2,
                pressure: 1004,
                sea_level: 1004,
                grnd_level: 977,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13d' }],
            clouds: { all: 100 },
            wind: { speed: 5.58, deg: 17, gust: 11.47 },
            visibility: 139,
            pop: 1,
            snow: { '3h': 5.4 },
            sys: { pod: 'd' },
            dt_txt: '2022-12-11 09:00:00',
        },
        {
            dt: 1670760000,
            main: {
                temp: 272.27,
                feels_like: 267.28,
                temp_min: 272.27,
                temp_max: 272.27,
                pressure: 1002,
                sea_level: 1002,
                grnd_level: 975,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13d' }],
            clouds: { all: 100 },
            wind: { speed: 4.76, deg: 4, gust: 10.08 },
            visibility: 139,
            pop: 1,
            snow: { '3h': 3.67 },
            sys: { pod: 'd' },
            dt_txt: '2022-12-11 12:00:00',
        },
        {
            dt: 1670770800,
            main: {
                temp: 271.64,
                feels_like: 266.63,
                temp_min: 271.64,
                temp_max: 271.64,
                pressure: 1003,
                sea_level: 1003,
                grnd_level: 976,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 4.55, deg: 349, gust: 9.75 },
            visibility: 152,
            pop: 1,
            snow: { '3h': 1.92 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-11 15:00:00',
        },
        {
            dt: 1670781600,
            main: {
                temp: 271.16,
                feels_like: 266.58,
                temp_min: 271.16,
                temp_max: 271.16,
                pressure: 1003,
                sea_level: 1003,
                grnd_level: 976,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 3.79, deg: 331, gust: 8.55 },
            visibility: 148,
            pop: 1,
            snow: { '3h': 1.56 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-11 18:00:00',
        },
        {
            dt: 1670792400,
            main: {
                temp: 270.69,
                feels_like: 266.76,
                temp_min: 270.69,
                temp_max: 270.69,
                pressure: 1004,
                sea_level: 1004,
                grnd_level: 977,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 2.93, deg: 311, gust: 6.97 },
            visibility: 140,
            pop: 0.97,
            snow: { '3h': 1.26 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-11 21:00:00',
        },
        {
            dt: 1670803200,
            main: {
                temp: 270.46,
                feels_like: 266.35,
                temp_min: 270.46,
                temp_max: 270.46,
                pressure: 1003,
                sea_level: 1003,
                grnd_level: 976,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 3.07, deg: 302, gust: 6.97 },
            visibility: 155,
            pop: 0.98,
            snow: { '3h': 1.26 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-12 00:00:00',
        },
        {
            dt: 1670814000,
            main: {
                temp: 270.31,
                feels_like: 265.49,
                temp_min: 270.31,
                temp_max: 270.31,
                pressure: 1004,
                sea_level: 1004,
                grnd_level: 977,
                humidity: 97,
                temp_kf: 0,
            },
            weather: [{ id: 601, main: 'Snow', description: 'snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 3.86, deg: 280, gust: 7.34 },
            visibility: 141,
            pop: 1,
            snow: { '3h': 1.93 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-12 03:00:00',
        },
        {
            dt: 1670824800,
            main: {
                temp: 270.17,
                feels_like: 264.82,
                temp_min: 270.17,
                temp_max: 270.17,
                pressure: 1005,
                sea_level: 1005,
                grnd_level: 977,
                humidity: 96,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 4.53, deg: 269, gust: 8.46 },
            visibility: 181,
            pop: 1,
            snow: { '3h': 1.31 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-12 06:00:00',
        },
        {
            dt: 1670835600,
            main: {
                temp: 270.88,
                feels_like: 265.15,
                temp_min: 270.88,
                temp_max: 270.88,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 979,
                humidity: 95,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13d' }],
            clouds: { all: 99 },
            wind: { speed: 5.4, deg: 261, gust: 8.76 },
            visibility: 764,
            pop: 0.68,
            snow: { '3h': 0.42 },
            sys: { pod: 'd' },
            dt_txt: '2022-12-12 09:00:00',
        },
        {
            dt: 1670846400,
            main: {
                temp: 272.01,
                feels_like: 266.31,
                temp_min: 272.01,
                temp_max: 272.01,
                pressure: 1005,
                sea_level: 1005,
                grnd_level: 978,
                humidity: 93,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13d' }],
            clouds: { all: 96 },
            wind: { speed: 5.89, deg: 264, gust: 9.37 },
            visibility: 3218,
            pop: 0.48,
            snow: { '3h': 0.14 },
            sys: { pod: 'd' },
            dt_txt: '2022-12-12 12:00:00',
        },
        {
            dt: 1670857200,
            main: {
                temp: 270.97,
                feels_like: 265.41,
                temp_min: 270.97,
                temp_max: 270.97,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 979,
                humidity: 94,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 5.16, deg: 257, gust: 10.54 },
            visibility: 1344,
            pop: 0.36,
            snow: { '3h': 0.13 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-12 15:00:00',
        },
        {
            dt: 1670868000,
            main: {
                temp: 269.08,
                feels_like: 263.85,
                temp_min: 269.08,
                temp_max: 269.08,
                pressure: 1007,
                sea_level: 1007,
                grnd_level: 980,
                humidity: 95,
                temp_kf: 0,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04n' }],
            clouds: { all: 95 },
            wind: { speed: 4.02, deg: 250, gust: 9.21 },
            visibility: 8505,
            pop: 0.09,
            sys: { pod: 'n' },
            dt_txt: '2022-12-12 18:00:00',
        },
        {
            dt: 1670878800,
            main: {
                temp: 267.72,
                feels_like: 262.92,
                temp_min: 267.72,
                temp_max: 267.72,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 981,
                humidity: 95,
                temp_kf: 0,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04n' }],
            clouds: { all: 87 },
            wind: { speed: 3.2, deg: 241, gust: 8.06 },
            visibility: 3839,
            pop: 0.05,
            sys: { pod: 'n' },
            dt_txt: '2022-12-12 21:00:00',
        },
        {
            dt: 1670889600,
            main: {
                temp: 268.13,
                feels_like: 263.63,
                temp_min: 268.13,
                temp_max: 268.13,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 980,
                humidity: 95,
                temp_kf: 0,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04n' }],
            clouds: { all: 93 },
            wind: { speed: 2.99, deg: 254, gust: 7.82 },
            visibility: 10000,
            pop: 0.05,
            sys: { pod: 'n' },
            dt_txt: '2022-12-13 00:00:00',
        },
        {
            dt: 1670900400,
            main: {
                temp: 267.49,
                feels_like: 262.74,
                temp_min: 267.49,
                temp_max: 267.49,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 981,
                humidity: 96,
                temp_kf: 0,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04n' }],
            clouds: { all: 97 },
            wind: { speed: 3.11, deg: 245, gust: 6.46 },
            visibility: 4506,
            pop: 0.05,
            sys: { pod: 'n' },
            dt_txt: '2022-12-13 03:00:00',
        },
        {
            dt: 1670911200,
            main: {
                temp: 268.84,
                feels_like: 263.9,
                temp_min: 268.84,
                temp_max: 268.84,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 980,
                humidity: 94,
                temp_kf: 0,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04n' }],
            clouds: { all: 98 },
            wind: { speed: 3.61, deg: 241, gust: 8.94 },
            visibility: 10000,
            pop: 0,
            sys: { pod: 'n' },
            dt_txt: '2022-12-13 06:00:00',
        },
        {
            dt: 1670922000,
            main: {
                temp: 269.53,
                feels_like: 265.08,
                temp_min: 269.53,
                temp_max: 269.53,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 981,
                humidity: 92,
                temp_kf: 0,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04d' }],
            clouds: { all: 96 },
            wind: { speed: 3.23, deg: 253, gust: 8.14 },
            visibility: 10000,
            pop: 0.11,
            sys: { pod: 'd' },
            dt_txt: '2022-12-13 09:00:00',
        },
        {
            dt: 1670932800,
            main: {
                temp: 271.18,
                feels_like: 265.93,
                temp_min: 271.18,
                temp_max: 271.18,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 981,
                humidity: 92,
                temp_kf: 0,
            },
            weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04d' }],
            clouds: { all: 98 },
            wind: { speed: 4.74, deg: 266, gust: 8.47 },
            visibility: 10000,
            pop: 0.12,
            sys: { pod: 'd' },
            dt_txt: '2022-12-13 12:00:00',
        },
        {
            dt: 1670943600,
            main: {
                temp: 270.71,
                feels_like: 265.66,
                temp_min: 270.71,
                temp_max: 270.71,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 981,
                humidity: 94,
                temp_kf: 0,
            },
            weather: [{ id: 600, main: 'Snow', description: 'light snow', icon: '13n' }],
            clouds: { all: 100 },
            wind: { speed: 4.29, deg: 284, gust: 8.82 },
            visibility: 10000,
            pop: 0.49,
            snow: { '3h': 0.15 },
            sys: { pod: 'n' },
            dt_txt: '2022-12-13 15:00:00',
        },
    ],
    city: {
        id: 3094802,
        name: 'Krakow',
        coord: { lat: 50.0833, lon: 19.9167 },
        country: 'PL',
        population: 755050,
        timezone: 3600,
        sunrise: 1670480753,
        sunset: 1670510322,
    },
};

let temperature = [];
let temperatureMode = [];
const beforeDeduped = [];
const daysArr = testArr1.list.map((el, i) => {
    temperature.push(el.main.temp);
    temperatureMode.push(parseInt(String(el.main.temp)));
    const day = new Date(`${el.dt_txt}`).getDay();
    return day;
});

// console.log(temperatureMode);
const max = Math.max(...temperature);
const min = Math.min(...temperature);
const maxIndex = temperature.indexOf(max);
const minIndex = temperature.indexOf(min);
// console.log(obj.list[minIndex].dt);
// console.log(obj.list[maxIndex].dt);

let temp = 0;
let amount = 0;
let testDays = [];
// console.log(daysArr);
daysArr.forEach((el, i) => {
    beforeDeduped.push(daysArr.indexOf(el));
    beforeDeduped.push(daysArr.lastIndexOf(el));
});
const deduped = [...new Set(beforeDeduped)];
const finished = [];
deduped.forEach((el, i) => {
    if ((1 + i) % 2 === 0) {
        let slice = obj.list.slice(deduped[i - 1], deduped[i + 1]);
        // console.log(slice.length);
        finished.push(slice);
    }
});
console.log(finished);
