import Head from 'next/head';
import { PageWrapper, MainApp, StatusComponent } from 'components';
import type { IGetWeatherIndexes } from 'utils/getWeatherIndexes';
import { useEffect, useState } from 'react';

interface Data {
    indexesObj: IGetWeatherIndexes | null;
    error: string | null;
}

export default function Home() {
    const [weatherObjects, setWeatherObject] = useState<IGetWeatherIndexes | null>(null);
    const [error, setError] = useState<string | null>(null);
    useEffect(() => {
        (async () => {
            const response = await fetch('/api/getWeatherByIP');
            const { indexesObj, error }: Data = await response.json();
            if (error) {
                setError(error);
                return;
            }
            setWeatherObject(indexesObj);
        })();
    }, []);

    if (error) {
        return <StatusComponent className="bg-pageBG flex justify-center" message={error} />;
    }

    if (!weatherObjects) {
        return <StatusComponent className="bg-pageBG flex justify-center" message="Loading" />;
    }

    return (
        <PageWrapper className="bg-pageBG flex justify-center">
            <Head>
                <title>Weather APP</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainApp weatherObjects={weatherObjects && weatherObjects} />
        </PageWrapper>
    );
}
