import Head from 'next/head';
import { PageWrapper, MainApp, StatusComponent, CitySetter } from 'components';
import type { IGetWeatherIndexes } from 'utils/getWeatherIndexes';
import { useEffect, useState } from 'react';
import { useLocation } from 'hooks/useLocation';

interface Data {
    indexesObj: IGetWeatherIndexes | null;
    error: string | null;
}

export default function Home() {
    const [city, setCity] = useState<string>('');
    const [weatherObjects, error] = useLocation(city);

    function setCityName(inputValue: string) {
        setCity(inputValue);
    }

    if (error) {
        return <StatusComponent className="bg-pageBG flex justify-center" message={error} />;
    }

    if (city && !weatherObjects) {
        return <StatusComponent className="bg-pageBG flex justify-center" message="Loading" />;
    }
    return (
        <PageWrapper className="bg-pageBG flex justify-center">
            <Head>
                <title>Weather APP</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {!city ? (
                <CitySetter setCity={setCityName} />
            ) : (
                <MainApp weatherObjects={weatherObjects && weatherObjects} />
            )}
        </PageWrapper>
    );
}
