import Head from 'next/head';
import { useEffect } from 'react';
import { TimeCityBox, PageWrapper } from 'components';
import dayjs from 'dayjs';
// Dec 8, 06:48pm
export default function Home() {
    // useEffect(() => {
    //     fetch('api/getIp')
    //         .then(res => res.json())
    //         .then(d => console.log(d));
    // }, []);
    return (
        <PageWrapper className="">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TimeCityBox time={dayjs().format('MMM DD, HH:mm')} city="London, UK" />
        </PageWrapper>
    );
}
